### ISSUE TITLE
Mounting /etc/passwd from container host causes problems

### ISSUE THREAD

**Issue by lachlancooper** [DataDog/documentation#1927]
## Documentation Page

https://docs.datadoghq.com/graphing/infrastructure/process/

## Issue Description 

The page suggests mounting `/etc/passwd` into docker-dd-agent to collect usernames for each process. This seems like a bad idea for two reasons:

1. It doesn't actually work very well. While usernames are collected for processes running directly on the host, other containers use their own `/etc/passwd` files. The agent has no way to access these and can't retrieve usernames for their processes.

   For example, the official Redis Docker container creates a `redis` user, UID 999. This isn't mapped by the agent and thus the username column for the redis-server process in the interface is empty.

2. It overrides the expected `/etc/passwd` file for docker-dd-agent, potentially causing problems with the agent itself.

   For example, I discovered this issue when I tried to troubleshoot an agent container and received:

   ```
   ~ $ docker exec -it 7f7986dc264e /etc/init.d/datadog-agent configcheck
   Cannot execute /bin/ash
   ```

   I eventually tracked this down to the fact that `root` on my Docker host uses the shell `/bin/ash`, which doesn't exist inside the agent container. This causes the various `su $AGENTUSER` commands in `/etc/init.d/datadog-agent` to fail with the above message.

## Potential solutions

At first glance I can't see an easy workaround for either problem. 1. seems unavoidable without a lot of work to retrieve or mount files from other containers. 2. seems potentially fixable by mounting the file elsewhere (e.g. `/host/etc/passwd`), but looking at the `datadog-process-agent` code it uses golang's `os/user.LookupId()`. This is hard-coded to use `/etc/passwd`.

Until the inherent issue is addressed, I think the best option is to accept that username collection is broken on container hosts, and remove these instructions (or at least note the significant caveats) from the documentation.

**Comment by mikezvi** [comment]
Thanks for the comment here.  In the short term we will add a note to the docs page to this effect, and then queue up some work to address the mount location as well.

**Comment by l0k0ms** [comment]
https://github.com/DataDog/documentation/pull/1995

**Comment by l0k0ms** [comment]
Hello @lachlancooper,

Many thanks for this feedback 🙇  
We just merged a PR to warn our users about this effect

If you notice other glitches in our doc feel free to open another issue here.
Keep it up with the good work!
Best regards,
Pierre

**Comment by armenr** [comment]
I'm still getting bitten by this, and it's 2021. 

I've got a kubernetes cluster running k3s, and installing the datadog helm chart only works partially (the process agent is broken due to this /etc/passwd mount problem). 

In this half-working state, if you pause/stop the cluster than attempt to start it again, the cluster errors out and won't start.

The best fix I've been able to find so far comes from here: https://github.com/DataDog/helm-charts/issues/273#issuecomment-855229431

What is the way to work around/amend/fix this in a kubernetes/k3s environment?

**Comment by JamesXNelson** [comment]
As a suggestion... if you want to mount `/etc/passwd`, you should probably mount `/etc/shadow` and `/etc/group` as well.

If you are hoping to use your host machine user inside the container, you probably need to mount `/home/you:/home/you` as well.
